### PR TITLE
Upgrade to Ubuntu-14.04 and upstart init scripts.

### PR DESCRIPTION
**Pull request by dashohoxha**
However isso does not work, needs to be fixed.

### CODE REVIEW

**Comment by blankoworld** [comment]
Thanks for the pull request. I will have a look this week.

However I use this docker from 6 months on Ubuntu 12.04 server. It's curious that you said it doesn't work on your side. Which version of docker? Which ubuntu version?

Keep also in mind that the docker-isso is useful to launch multiple instances of Isso. One docker = one isso instance/server.
So why using ubuntu-upstart? Why adding more complexity? The more lines you have, the more bug you can have in the future.

I will check this week if this pull request is compatible with scripts I use to make an Isso free service.

**Comment by dashohoxha** [comment]
I said that **sshd** was not working, because I didn't see where *supervisord* was starting.

Usually you cannot run `/sbin/init` inside a normal Ubuntu container, because *upstart* (the init script of ubuntu) is nasty (has some problems). The image **ubuntu-upstart** has fixed these problems and runs the command `/sbin/init` by default. This seems to me more normal/natural than running **supervisor** (maybe because I tend to use docker containers like lightweight virtual machines).

However, the image and the container that these scripts (that I am suggesting) generate, do not work (**isso** does not start). This is because I don't have experience with **isso** installation and cannot fix it (at least not without spending lots of time). So, you can either keep these changes and fix them so that **isso** works, or discard them and only pick up some ideas (for example using ubuntu **14.04**).

**Comment by dashohoxha** [comment]
Now it builds and runs correctly, however don't see `gevent` anywhere. Maybe there is something to be improved or fixed, but I am totally ignorant about gunicorn/gevent/python.

**Comment by dashohoxha** [comment]
I will also try to make a docker image based on debian (instead of ubuntu-upstart), which is supposed to be better because it does not have `upstart` (which doesn't play well with virtual machines).

**Comment by dashohoxha** [comment]
I think that the debian based image is better that this one.

**Pull request closed without merging**
